enum tokens { NUMBER, DOT, COLON, AM, PM, NOON, MIDNIGHT, TEATIME, TODAY,
	      TONIGHT, TOMORROW, DAY, WEEK, MONTH, YEAR, FROM, NOW,  NEXT,
	      MINUTE, HOUR, DASH, SLASH, PLUS, MONTHNAME,  ERROR };
