#! /bin/sh

last=
while IFS=':' read action line;do
    if [ "$action" = '#' -o -n "$line" ]; then
	if [ "$last" != "$action" ]; then
	    echo
	    case "$action" in
	    y) what="Expecting success" ;;
	    n) what="Expecting failure" ;;
	    *) what="Time-dependent tests" ;;
	    esac
	    echo "$what:"
	    echo
	    last=$action
	fi
	MSG=`./at -d2 $line 2>&1`
	rc=$?

	txt=`echo "$line                                        " | cut -c 1-32`

	echo -n "	$txt "
	case $action in
	y) test "$rc" -eq 0 && echo "passed" || echo "failed" ;;
	n) test "$rc" -eq 0 && echo "failed" || echo "passed" ;;
	*) test "$rc" -eq 0 && echo "rc=0" || echo "$MSG"   ;;
	esac
    fi
done
test -z "$last" || echo
exit 0
