#! /bin/sh

last=
while IFS=':' read action line;do
    if [ "$action" = '#' -o -n "$line" ]; then
	if [ "$last" != "$action" ]; then
	    echo
	    case "$action" in
	    y) what="Expecting success" ;;
	    n) what="Expecting failure" ;;
	    *) what="Time-dependent tests" ;;
	    esac
	    echo "$what:"
	    echo
	    last=$action
	fi
	MSG=`./at -d2 $line 2>&1`
	rc=$?

	txt=`echo "$line                                        " | cut -c 1-32`

	/bin/echo -n "	$txt "
	case $action in
	y)  if test "$rc" -eq 0 ; then
		echo "passed"
	    else
		echo "failed"
		(( failed ++ ))
	    fi ;;
	n) if test "$rc" -eq 0 ; then
		echo "failed"
		(( failed ++ ))
	    else
		echo "passed"
	    fi ;;
	*) test "$rc" -eq 0 && echo "ok" || echo "$MSG"   ;;
	esac
    fi
done
test -z "$last" || echo
exit $failed
